-- MySQL Script generated by MySQL Workbench
-- Tue Nov 12 17:21:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema centreFormation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema centreFormation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `centreFormation` DEFAULT CHARACTER SET utf8 ;
USE `centreFormation` ;

-- -----------------------------------------------------
-- Table `centreFormation`.`etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`etudiant` (
  `numCINEtu` VARCHAR(10) NOT NULL,
  `nomEtu` VARCHAR(45) NULL,
  `prenomEtu` VARCHAR(45) NULL,
  `datenais` DATE NULL,
  `villeEtu` VARCHAR(45) NULL,
  `niveauEtu` VARCHAR(45) NULL,
  PRIMARY KEY (`numCINEtu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centreFormation`.`formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`formation` (
  `codeForm` INT NOT NULL,
  `titreForm` VARCHAR(45) NULL,
  `dureeForm` DECIMAL(5) NULL,
  `prixForm` DECIMAL(5) NULL,
  PRIMARY KEY (`codeForm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centreFormation`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`session` (
  `idsession` INT NOT NULL,
  `nomsess` VARCHAR(45) NULL,
  `datedebut` DATE NULL,
  `codeForm` VARCHAR(10) NULL,
  `dateFin` DATE NULL,
  `formation_codeForm` INT NOT NULL,
  PRIMARY KEY (`idsession`),
  INDEX `CHECK` () COMMENT 'dateFin > datedebut' VISIBLE,
  INDEX `fk_session_formation1_idx` (`formation_codeForm` ASC) VISIBLE,
  CONSTRAINT `codeForm`
    FOREIGN KEY ()
    REFERENCES `centreFormation`.`formation` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_formation1`
    FOREIGN KEY (`formation_codeForm`)
    REFERENCES `centreFormation`.`formation` (`codeForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centreFormation`.`inscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`inscription` (
  `codesess` INT NOT NULL,
  `numCINEtu` VARCHAR(10) NOT NULL,
  `typeCours` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codesess`, `numCINEtu`),
  CONSTRAINT `codesess`
    FOREIGN KEY ()
    REFERENCES `centreFormation`.`session` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `numCINEtu`
    FOREIGN KEY ()
    REFERENCES `centreFormation`.`etudiant` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centreFormation`.`specialite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`specialite` (
  `codeSpec` INT NOT NULL,
  `nomSpec` VARCHAR(45) NULL,
  `descSpec` VARCHAR(100) NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`codeSpec`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centreFormation`.`combinaison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`combinaison` (
  `codeSpec` INT NOT NULL,
  `codeForm` INT NOT NULL,
  PRIMARY KEY (`codeSpec`, `codeForm`),
  CONSTRAINT `codeSpec`
    FOREIGN KEY ()
    REFERENCES `centreFormation`.`specialite` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codeForm`
    FOREIGN KEY ()
    REFERENCES `centreFormation`.`formation` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
